---
title: "South Bend Violence within City Council Districts"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(jsonlite)
library(maptools)
library(ggplot2)
library(tidyr)
library(dplyr)
library(purrr)
library(leaflet)
library(sf)




# city_council <- st_read("City_Council_Districts/City_Council_Districts.shp")
# 
# pol_forc <- st_read("Police_Use_of_Force_Incidents/Police_Use_of_Force_Incidents.shp" )%>%
#   mutate(year=lubridate::year(Date))
# 
# shootings <- st_read("Criminally_Assaulted_Shootings.shp")
# 
# map_df <- shootings %>%
#   select(year = USER_Year, fatal = USER_Fatal) %>%
#   mutate(incident_type = "shooting") %>% 
#   rbind(pol_forc %>% 
#   mutate(year = lubridate::year(Date)) %>%
#   mutate(incident_type = "force") %>% 
#   mutate(fatal = NA) %>%
#   select(year, fatal, incident_type))
# 
# shootings.df <- shootings %>% st_set_geometry(NULL)
# remote_data <- st_join(x = city_council, map_df)
# remote_data.df <- remote_data %>% st_set_geometry(NULL)
# pol_forc.df <- pol_forc  %>% st_set_geometry(NULL)
# 
# save(shootings.df, pol_forc.df, remote_data.df, pol_forc, shootings, remote_data, file="remote_data.rda")
load('remote_data.rda')


pal <- colorNumeric(
  palette = "OrRd",
  domain = 0:40
)


```


Sidebar {.sidebar}
=======================================================================

### <strong>Dashboard Controls<strong>


```{r}



selectInput(inputId = "incident", label = h3("Incident Type"), 
            choices = list("Criminal Shooting" = "shooting", "Police use of Force" = "force"), selected = "shooting")

selectInput(inputId = "year", label = h3("Years"), 
            choices = list("2017" = 2017, "2018" = 2018, "2019" = 2019), selected = 2019)


selectInput(inputId = "points", label = h3("Show locations"), 
            choices = list("Yes" = TRUE, "No" = FALSE), selected = FALSE)

```

#### Contacts

```{r, f}

remote_data.df %>% 
  select(Council_Me, Email, Dist, Num) %>%
  filter(!duplicated(.)) %>% 
  rename(`Council Member Name`=Council_Me, District=Dist) %>% 
  knitr::kable() %>% 
  kableExtra::kable_styling(font_size = 8)




```



Dashboard
=======================================================================

Row
-----------------------------------------------------------------------

### Criminal Shootings {.value-box}

```{r}

total.shootings <- reactive({
  shootings.df %>% 
    filter(USER_Year == input$year) %>% 
    group_by(USER_Year) %>% 
    summarise(count=n()) %>%
    .$count %>% 
    return()
})


renderValueBox({

  
  valueBox(
    value = total.shootings(),
    #icon = "fa-area-chart",
    color = if (total.shootings() >=100) "warning" else "primary"
  )
})
```

### Fatal Criminal Shooting {.value-box}

```{r}
total.fatal <- reactive({
  tmp <- shootings.df %>% 
    filter(USER_Year == input$year, USER_Fatal == 'Yes') %>% 
    group_by(USER_Year) %>% 
    summarise(count=n()) %>%
    .$count %>% 
    return()
})


renderValueBox({

  
  valueBox(
    value = paste0(round((total.fatal() / total.shootings())*100,1),"%"),
    #icon = "fa-area-chart",
    #color = if (rate >= input$rateThreshold) "warning" else "primary"
  )
})
```

### Police Incidents {.value-box}

```{r}
Pol_inc <- reactive({
  tmp <- pol_forc.df %>% 
    filter(year == input$year) %>% 
    group_by(year) %>% 
    summarise(count=n()) %>%
    .$count %>% 
    return()
})


renderValueBox({

  
  valueBox(
    value = Pol_inc(),
    #icon = "fa-area-chart",
    color = if (Pol_inc() >= 60) "warning" else "primary"
  )
})
```


### Proportion of Police Injurred {.value-box}

```{r}
pol_inj <- reactive({
  tmp <- pol_forc.df %>% 
    filter(year == input$year, Off_Injure =="Yes") %>% 
    group_by(year) %>% 
    summarise(count=n()) %>%
    .$count %>% 
    return()
})


renderValueBox({

  
  valueBox(
    value = paste0(round((pol_inj() / Pol_inc())*100,1),"%"),
    #icon = "fa-area-chart",
    #color = if (rate >= input$rateThreshold) "warning" else "primary"
  )
})
```

Row
-----------------------------------------------------------------------

### Incidents in city Council Districts {data-width=600}

```{r}
map_reac <- reactive({
  tmp <- remote_data %>% 
    filter(year==input$year, incident_type == input$incident) %>% 
    group_by(Dist, year, Council_Me, Num) %>%
    summarise(count=n()) %>%
    return()
})

points_reac <- reactive({
 if(input$incident == 'Shooting'){
    tmp=shootings %>% 
     filter(USER_Year==input$year) %>% 
      rename(date = USER_Date, address = USER_Addre)
  }else{
    tmp=pol_forc %>% 
      filter(year==input$year) %>% 
      rename(date=Date, address = Blocked_Lo)
  } 
 return(tmp)
})

renderLeaflet({
  if(input$points){
      leaflet() %>% 
        addProviderTiles(providers$Stamen.Toner) %>% 
        addPolygons(data=map_reac(), color = "#d3d3d3", weight = 1, fillColor = ~pal(count), fillOpacity = .7) %>% 
        addMarkers(data=points_reac(),
                   clusterOptions = markerClusterOptions(),  
                   popup=paste0("<b>Date:</b> ", points_reac()$date,"<br>",
                                '<b>Address:</b> ', points_reac()$address)) %>% 
      addLegend("topright", pal = pal, values = 0:40,
    title = paste0("Incident Count: ", unique(map_reac()$year)),
    opacity = 1)
        
      
  }else{
      leaflet() %>% 
        addProviderTiles(providers$Stamen.Toner) %>% 
        addPolygons(data=map_reac(), color = "#d3d3d3", 
                    weight = 1, 
                    fillColor = ~pal(count), 
                    fillOpacity = .7, 
                    popup = paste0("<b>Council Member:</b> ", map_reac()$Council_Me,"<br>",
                                   '<b>District Number:</b> ', map_reac()$Num, "<br>",
                                   '<b>Incident Count:</b> ', map_reac()$count))%>% 
      addLegend("topright", pal = pal, values = 0:40,
    title = paste0("Incident Count: ", unique(map_reac()$year)),
    opacity = 1)
  }

})


```


### Underlying Data {data-width=440}

```{r}
tbl_df <- reactive({
  if(input$incident =="shooting"){
    tbl <- shootings.df %>% 
      filter(USER_Year==input$year) %>% 
      select(USER_Addre, USER_Date, USER_Fatal) %>% 
      rename(Date=USER_Date, Address=USER_Addre, Fatality=USER_Fatal)

  }else{
    tbl <- pol_forc.df %>% 
      filter(year==input$year) %>% 
      select(Date, Blocked_Lo, Shift, Force_Caus, Beat, Off_Injure, Call_Dispa, Call_in_Re, Response) %>%
      rename(`Forced Caused`=Force_Caus, `Off Duty Injured`=Off_Injure, `Call Dispatcher`=Call_Dispa, `Call In Response To`=Call_in_Re, `Address`=Blocked_Lo, `Violence Type`=Response)


  }
  return(tbl)
})

renderDataTable({tbl_df()})





```







